import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  icons:{
    icon : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0GcD4aysF_RB-HWqB70JuHdB9SBoRb_WAfw&s",

  },
  title:{
    default:"Chandana's Portfolio",
    template: " Chandana's  %s",
  }, 
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {/* <Footer/> */}
    </html>
  );
}
